# Generated by Django 5.1.2 on 2024-11-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_product_product_image_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="composition",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="prodapp",
            field=models.TextField(blank=True, default=""),
        ),
    ]
