# Generated by Django 5.1.2 on 2024-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_product_composition_alter_product_prodapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="composition",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="prodapp",
            field=models.TextField(default=""),
        ),
    ]
